apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-auditd
  namespace: kube-system
  labels:
    name: aks-auditd
spec:
  selector:
    matchLabels:
      name: aks-auditd
  template:
    metadata:
      labels:
        name: aks-auditd
    spec:
      hostPID: true
      initContainers:
      - name: init
        #image: ghcr.io/kipidestan/aks-auditd:latest
        image: auditacrtest123.azurecr.io/aks-auditd-init:22
        volumeMounts:
        - name: node
          mountPath: /node
        imagePullPolicy: Always
        securityContext:
          privileged: true
      containers:
      - name: aks-auditd
        #image: ghcr.io/kipidestan/aks-auditd:latest
        image: auditacrtest123.azurecr.io/aks-auditd:18
        env:
        - name: AA_LOG_LEVEL
          value: debug
        volumeMounts:
        - name: node
          mountPath: /node
        - name: auditd-rules
          mountPath: /auditd-rules
        - name: audisp-plugins
          mountPath: /audisp-plugins
        imagePullPolicy: Always
        securityContext:
          privileged: true
          # runAsUser: 807
          # runAsGroup: 808
      volumes:
      - name: node
        hostPath:
          path: /
      - name: auditd-rules
        configMap:
          name: auditd-rules
      - name: audisp-plugins
        configMap:
          name: audisp-plugins
    
      

  

