apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-auditd
  namespace: kube-system
  labels:
    name: aks-auditd
spec:
  selector:
    matchLabels:
      name: aks-auditd
  template:
    metadata:
      labels:
        name: aks-auditd
    spec:
      hostPID: true   # This is required because of the systemctl command in aks-auditd-init. The container needs access to the host PID namespace to restart the auditd service. I may try to package the aks-auditd-monitor in a deb package to get around this in the future.
      initContainers:
      - name: init
        image: ghcr.io/kipidestan/aks-auditd-init:latest
        volumeMounts:
        - name: node
          mountPath: /node
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            drop:
            - ALL
            add:
            - SYS_CHMOD
            - SYS_CHOWN
            - SYS_CHROOT
      containers:
      - name: aks-auditd
        image: ghcr.io/kipidestan/aks-auditd-run:latest
        volumeMounts:
        - name: node
          mountPath: /node
        - name: auditd-rules
          mountPath: /auditd-rules
        - name: audisp-plugins
          mountPath: /audisp-plugins
        imagePullPolicy: Always
        securityContext:
          runAsUser: 807
          runAsGroup: 808
          capabilities:
            drop:
            - ALL
      volumes:
      - name: node
        hostPath:
          path: /
      - name: auditd-rules
        configMap:
          name: auditd-rules
      - name: audisp-plugins
        configMap:
          name: audisp-plugins
    
      

  

